name: Client Deployment Prod
on:
  release:
    types: [published]

defaults:
  run:
    working-directory: client/web

jobs:
  client:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    name: build & push client

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install
      - name: Build React App
        env:
          REACT_APP_MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
          REACT_APP_API_URL: https://api.ballotnav.org/public
          REACT_APP_MIXPANEL_TOKEN: ${{ secrets.MIXPANEL_TOKEN_PROD }}
          REACT_APP_HOTJAR_ID: ${{ secrets.HOTJAR_ID_PROD }}
        run: npm run build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: print current directory
        run: ls -la
      - name: Push to s3
        run: | 
          aws s3 sync build/ s3://ballotnav.org
          aws s3 cp build/index.html s3://ballotnav.org --cache-control no-cache
